# Generated by Django 3.2 on 2021-12-05 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
                ('nim', models.CharField(blank=True, max_length=100, null=True)),
                ('kelas', models.CharField(blank=True, max_length=100, null=True)),
                ('subjek', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileTugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filenya', models.FileField(max_length=200, upload_to='file/%Y/%m/%d')),
                ('tugas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.tugas')),
            ],
        ),
    ]
