# Generated by Django 3.2 on 2021-12-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20211214_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetugas',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='filetugas',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='tugas',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tugas',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
