# Generated by Django 3.2 on 2021-12-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20211215_0408'),
    ]

    operations = [
        migrations.AddField(
            model_name='tugas',
            name='absen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
