# Generated by Django 3.2 on 2021-12-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_tugas_absen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tugas',
            name='absen',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tugas',
            name='nim',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
